sonar.projectKey=split-openfeature-provider-android
sonar.projectName=Split OpenFeature Provider for Android
# Source and test directories
sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
# Java bytecode
sonar.java.binaries=build/tmp/kotlin-classes/debug
# JaCoCo coverage report path
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
# Encoding of the source code
sonar.sourceEncoding=UTF-8
