pipeline:
  name: split-openfeature-provider-android
  identifier: splitopenfeatureproviderandroid
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubdevops
        repoName: split-openfeature-provider-android
        build: <+input>
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Test
                  name: Run tests
                  identifier: Run_tests
                  spec:
                    shell: Sh
                    command: ./gradlew test
                    intelligenceMode: true
